package io.d2a.eeee.generate.random.generators.special;

import io.d2a.eeee.generate.random.generators.StringGenerator;
import java.util.Random;

public class NameGenerator extends StringGenerator {

    @Override
    public String generateString(final Random random, final int length) {
        return NAMES[random.nextInt(NAMES.length)];
    }

    public static final String[] NAMES = new String[]{
        "James",
        "Mary",
        "Robert",
        "Patricia",
        "John",
        "Jennifer",
        "Michael",
        "Linda",
        "William",
        "Elizabeth",
        "David",
        "Barbara",
        "Richard",
        "Susan",
        "Joseph",
        "Jessica",
        "Thomas",
        "Sarah",
        "Charles",
        "Karen",
        "Christophe",
        "Nancy",
        "Daniel",
        "Lisa",
        "Matthew",
        "Betty",
        "Anthony",
        "Margaret",
        "Mark",
        "Sandra",
        "Donald",
        "Ashley",
        "Steven",
        "Kimberly",
        "Paul",
        "Emily",
        "Andrew",
        "Donna",
        "Joshua",
        "Michelle",
        "Kenneth",
        "Dorothy",
        "Kevin",
        "Carol",
        "Brian",
        "Amanda",
        "George",
        "Melissa",
        "Edward",
        "Deborah",
        "Ronald",
        "Stephanie",
        "Timothy",
        "Rebecca",
        "Jason",
        "Sharon",
        "Jeffrey",
        "Laura",
        "Ryan",
        "Cynthia",
        "Jacob",
        "Kathleen",
        "Gary",
        "Amy",
        "Nicholas",
        "Shirley",
        "Eric",
        "Angela",
        "Jonathan",
        "Helen",
        "Stephen",
        "Anna",
        "Larry",
        "Brenda",
        "Justin",
        "Pamela",
        "Scott",
        "Nicole"
    };

}
